<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class artikelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jumlah = 5;
        foreach (range(1, $jumlah) as $index) {
            DB::table('artikel')->insert([
                'judul' => 'Bagian Judul'.$index,
                'deskripsi' => 'Contoh teks deksripi singkat mengenai materi atau artikel, teks ini hanyalah contoh demo tampilan saja. Generated by System...',
                'created_at' => now()
            ]);
        }        
    }
}
